import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import HeaderQuiz from "./ui/HeaderQuiz";
import ProviderStore from "./ui/ProviderStore";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable}  antialiased`}>
        <HeaderQuiz />

        <ProviderStore>{children}</ProviderStore>
        <div id="modal"></div>
      </body>
    </html>
  );
}
